In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
data = torch.Tensor([1., 2., 3.])

F.sigmoid(data,)

tensor([0.7311, 0.8808, 0.9526])

In [13]:

import torch
import torch.nn as nn
import torch.nn.functional as F


class Model(nn.Module):

    def __init__(self) -> None:
        super(Model, self).__init__()
        
        
        self.layer_1 = nn.Sequential(
            nn.Linear(in_features=4, out_features=4, bias=False),
        )
        self.layer_2 = nn.Sequential(
            nn.Linear(in_features=4, out_features=4, bias=False),
            nn.Linear(in_features=4, out_features=4, bias=False)
        )

    def block_1(self, data):
        self.block_1_layers = nn.Sequential(
            nn.Linear(64, 32)
        )
        return self.block_1_layers(data)


    def forward(self, data):
        data = self.layer_1(data)
        data = self.block_1(data)
        return data


In [14]:
model = Model()
print(model)

Model(
  (layer_1): Sequential(
    (0): Linear(in_features=4, out_features=4, bias=False)
  )
  (layer_2): Sequential(
    (0): Linear(in_features=4, out_features=4, bias=False)
    (1): Linear(in_features=4, out_features=4, bias=False)
  )
)


In [15]:
s = 0
for i in model.parameters():
    print(i)
    s += i.numel()
s

Parameter containing:
tensor([[-0.3472,  0.3798, -0.3819, -0.1995],
        [ 0.2743,  0.1120,  0.1799, -0.4946],
        [ 0.0899, -0.2928, -0.1689, -0.2226],
        [ 0.3388,  0.2206, -0.4926, -0.1186]], requires_grad=True)
Parameter containing:
tensor([[-0.0220,  0.2704, -0.1654,  0.0609],
        [-0.0274,  0.4132,  0.4500, -0.0290],
        [-0.1032,  0.2744,  0.0681,  0.1002],
        [ 0.2448,  0.0250,  0.1848,  0.3944]], requires_grad=True)
Parameter containing:
tensor([[-0.4689,  0.1073, -0.3669,  0.1737],
        [-0.1114,  0.1549,  0.2068, -0.4367],
        [-0.4147, -0.2603, -0.0417,  0.3834],
        [-0.0152,  0.1514,  0.3104, -0.4175]], requires_grad=True)


48